package org.agmas.harpymodloader.mixin.client;

import io.wifi.starrailexpress.api.Role;
import io.wifi.starrailexpress.cca.GameRoundEndComponent;
import io.wifi.starrailexpress.cca.GameWorldComponent;
import io.wifi.starrailexpress.client.gui.RoleAnnouncementTexts;
import io.wifi.starrailexpress.game.GameFunctions;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import org.agmas.harpymodloader.Harpymodloader;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

@Mixin(RoleAnnouncementTexts.RoleAnnouncementText.class)
public abstract class InnocenceReliantWinTextMixin {

    @Inject(method = "getEndText", at = @At("HEAD"), cancellable = true)
    private void b(GameFunctions.WinStatus status, Component winner, GameRoundEndComponent roundEnd,
            CallbackInfoReturnable<Component> cir) {
        GameWorldComponent gameWorldComponent = (GameWorldComponent) GameWorldComponent.KEY
                .get(Minecraft.getInstance().player.level());
        if (Harpymodloader.autogeneratedAnnouncements_flip
                .get((RoleAnnouncementTexts.RoleAnnouncementText) (Object) this) != null) {
            Role role = Harpymodloader.autogeneratedAnnouncements_flip
                    .get((RoleAnnouncementTexts.RoleAnnouncementText) (Object) this);
            switch (status) {
                case TIME:
                case PASSENGERS:
                    cir.setReturnValue(role.isInnocent() ? RoleAnnouncementTexts.CIVILIAN.winText
                            : RoleAnnouncementTexts.KILLER.getLoseText());
                    cir.cancel();
                    break;
                case KILLERS:
                    cir.setReturnValue(role.isInnocent() ? RoleAnnouncementTexts.CIVILIAN.getLoseText()
                            : RoleAnnouncementTexts.KILLER.winText);
                    cir.cancel();
                    break;
                default:
                    break;
            }
        }
    }
}
